### ISSUE TITLE
Error when we run test_lora.py

### ISSUE THREAD

**Issue by Diallomm** [mayeranalytics/pySX127x#30]
/home/pi/Git/Git-clone/pySX127x/SX127x/board_config.py:61: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(BOARD.LED, GPIO.OUT)
/home/pi/Git/Git-clone/pySX127x/SX127x/board_config.py:62: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(BOARD.RST, GPIO.OUT)
Traceback (most recent call last):
  File "test_lora.py", line 130, in <module>
    lora = LoRa(verbose=False)
  File "/home/pi/Git/Git-clone/pySX127x/SX127x/LoRa.py", line 95, in __init__
    BOARD.add_events(self._dio0, self._dio1, self._dio2, self._dio3, self._dio4, self._dio5)
  File "/home/pi/Git/Git-clone/pySX127x/SX127x/board_config.py", line 105, in add_events
    BOARD.add_event_detect(BOARD.DIO0, callback=cb_dio0)
  File "/home/pi/Git/Git-clone/pySX127x/SX127x/board_config.py", line 101, in add_event_detect
    GPIO.add_event_detect(dio_number, GPIO.RISING, callback=callback)
RuntimeError: Failed to add edge detection

**Comment by mayeranalytics** [comment]
I means the BOARD class is trying to set up GPIO pins that are already in use.
